version: '3.8'

services:
  ema-ha-strategy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    command: --config config/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, os; sys.exit(0 if os.path.exists('data/results') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
